from typing import Protocol, List, Optional
from app.schemas.book import Book, BookCreate, BookUpdate

class BookRepositoryInterface(Protocol):
    def get_books(self) -> List[Book]: ...
    def get_book(self, book_id: int) -> Optional[Book]: ...
    def add_book(self, book_create: BookCreate) -> Book: ...
    def update_book(self, book_id: int, book_update: BookUpdate) -> Optional[Book]: ...
    def delete_book(self, book_id: int) -> bool: ...
